version: '3.9'
services:
  tg_bot:
    container_name: expense_accounting
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
      # TODO Написать команду запуска
#    entrypoint: [
#      "poetry", "run", "uvicorn", "app:create_app",
#      "--host", "0.0.0.0",
#      "--port", '5001',
#    ]
    networks:
      - ea-network
    depends_on:
      - postgres
      - kafka

  postgres:
    image: postgres:17.0-bookworm
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_USER}
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/expense_accounting
    ports:
      - "5432:5432"
    networks:
      - ea-network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka_container
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093
      KAFKA_LISTENER_NAME_INSIDE: INSIDE
      KAFKA_LISTENER_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - ea-network
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - ea-network

volumes:
  postgres_data:

networks:
  ea-network:
    driver: bridge